# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

# Uncomment this line if you're using Swift
use_frameworks!

target 'Translation' do

  pod 'googleapis', :path => '.'
  pod 'AuthLibrary', :git => 'https://github.com/google/auth-library-swift.git'
  pod 'MaterialComponents'
  pod 'Firebase/Messaging'

end


